// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/style-guide": {
    params: {};
  };
  "/rsvp": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sitemap.xml" | "/style-guide" | "/rsvp" | "/robots.txt" | "/*";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[style-guide]._index.tsx": {
    id: "routes/[style-guide]._index";
    page: "/style-guide";
  };
  "routes/[rsvp]._index.tsx": {
    id: "routes/[rsvp]._index";
    page: "/rsvp";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[style-guide]._index": typeof import("./app/routes/[style-guide]._index.tsx");
  "routes/[rsvp]._index": typeof import("./app/routes/[rsvp]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};